name: CI

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401 # v2
        with:
          php-version: '8.2.0'
          tools: composer:v2.2

      - name: Install Dependencies
        run: composer install --no-progress --prefer-dist --no-suggest

      - name: Clone Wiki Repo (Authenticated)
        run: |
          git clone https://x-access-token:${{ secrets.WIKI_PAT }}@github.com/${{ github.repository }}.wiki.git wiki
          cd wiki
          git remote set-url origin https://x-access-token:${{ secrets.WIKI_PAT }}@github.com/${{ github.repository }}.wiki.git

      - name: Run PHPUnit and Save Coverage Report to Wiki
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d-%H-%M-%S")
          WIKI_PAGE="wiki/Code-Coverage-$TIMESTAMP.md"

          echo "# Code Coverage Report – $TIMESTAMP" > $WIKI_PAGE
          echo "" >> $WIKI_PAGE
          echo "\`\`\`" >> $WIKI_PAGE

          XDEBUG_MODE=coverage php vendor/bin/phpunit \
            -c dev/tests/unit/phpunit.xml \
            --testsuite Magento_GRA \
            --coverage-filter=app/code/ \
            --coverage-text | tee -a $WIKI_PAGE

          echo "\`\`\`" >> $WIKI_PAGE

      - name: Commit & Push Coverage Report to Wiki
        run: |
          cd wiki
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Add code coverage report – $(date)" || echo "No changes to commit"
          git push origin master
